name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
      
jobs:

  terraform-validate:
    uses: ./.github/workflows/terraform-check.yml
    with:
      working-directory: ${{ inputs.working-directory }}
    secrets: inherit

  terraform-plan:
    needs: terraform-validate
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit