name: Terraform CI

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: "."
      workspaces:
        type: string
        default: '["default"]'
      
jobs:

  terraform-plan:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

  terraform-apply:
    strategy:
      matrix:
        workspace: ${{fromJson(inputs.workspaces)}}
    needs: terraform-plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working-directory: ${{ inputs.working-directory }}
      workspace: ${{ matrix.workspace }}
    secrets: inherit

